import { jsPDF } from "jspdf";
import type { SignalPacket } from "./types";

export function generateReport(packet: SignalPacket) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 25;

  function addFooter() {
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(160);
    doc.text("Generated by Prelume", margin, pageHeight - 10);
    doc.text(
      new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
      pageWidth - margin,
      pageHeight - 10,
      { align: "right" }
    );
    doc.setTextColor(0);
  }

  function checkPage(needed: number) {
    if (y + needed > pageHeight - 20) {
      addFooter();
      doc.addPage();
      y = 25;
    }
  }

  function addSectionTitle(title: string) {
    checkPage(16);
    doc.setDrawColor(220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(50);
    doc.text(title.toUpperCase(), margin, y);
    y += 10;
  }

  function addItem(text: string) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60);
    const lines = doc.splitTextToSize(`\u2022  ${text}`, maxWidth - 4);
    checkPage(lines.length * 5 + 2);
    doc.text(lines, margin + 2, y);
    y += lines.length * 5 + 2;
  }

  function addLabelValue(label: string, value: string) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(120);
    doc.text(label.toUpperCase(), margin + 2, y);
    y += 5;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60);
    const lines = doc.splitTextToSize(value, maxWidth - 4);
    checkPage(lines.length * 5 + 4);
    doc.text(lines, margin + 2, y);
    y += lines.length * 5 + 4;
  }

  // ─── HEADER ───────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(150);
  doc.text("PRELUME", margin, y);
  y += 12;

  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30);
  doc.text("Signal Packet", margin, y);
  y += 12;

  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50);
  const titleLines = doc.splitTextToSize(
    `${packet.roleName} at ${packet.companyName}`,
    maxWidth
  );
  doc.text(titleLines, margin, y);
  y += titleLines.length * 7 + 4;

  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Confidence Score: ${packet.confidenceScore}%`, margin, y);
  y += 12;

  // ─── YOUR EDGE ────────────────────────────────────────
  if (packet.marketSignal.positioning) {
    checkPage(24);
    doc.setFillColor(240, 247, 255);
    doc.roundedRect(margin, y - 4, maxWidth, 22, 3, 3, "F");

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 102, 204);
    doc.text("YOUR EDGE", margin + 6, y + 2);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40);
    const edgeLines = doc.splitTextToSize(
      packet.marketSignal.positioning,
      maxWidth - 12
    );
    doc.text(edgeLines, margin + 6, y + 10);
    y += 26;
  }

  // ─── COMPANY SIGNALS ──────────────────────────────────
  addSectionTitle("Company Signals");
  addLabelValue("Hiring Urgency", packet.companySignal.urgency);
  addLabelValue("Growth Trajectory", packet.companySignal.growth);
  if (packet.companySignal.events.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(120);
    doc.text("RECENT EVENTS", margin + 2, y);
    y += 5;
    for (const e of packet.companySignal.events) addItem(e);
  }
  y += 4;

  // ─── HIDDEN EXPECTATIONS ──────────────────────────────
  addSectionTitle("Hidden Expectations");
  for (const e of packet.roleSignal.hiddenExpectations) addItem(e);
  y += 4;

  // ─── KEY TRAITS ───────────────────────────────────────
  addSectionTitle("Key Traits & Requirements");
  for (const e of packet.roleSignal.keyTraits) addItem(e);
  y += 4;

  // ─── RISKS ────────────────────────────────────────────
  if (packet.roleSignal.skillGaps.length > 0) {
    addSectionTitle("Risks & Skill Gaps");
    for (const e of packet.roleSignal.skillGaps) addItem(e);
    y += 4;
  }

  // ─── MARKET SIGNALS ───────────────────────────────────
  addSectionTitle("Market Signals");
  addLabelValue("Applicant Volume", packet.marketSignal.applicantVolume);
  addLabelValue("Competition Level", packet.marketSignal.competition);
  y += 4;

  // ─── STRATEGY ─────────────────────────────────────────
  addSectionTitle("How You Win This Role");
  packet.strategy.forEach((s, i) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60);
    const lines = doc.splitTextToSize(`${i + 1}.  ${s}`, maxWidth - 4);
    checkPage(lines.length * 5 + 4);
    doc.text(lines, margin + 2, y);
    y += lines.length * 5 + 4;
  });

  // ─── FOOTER ───────────────────────────────────────────
  addFooter();

  const slug =
    packet.companyName.toLowerCase().replace(/\s+/g, "-") || "signal";
  doc.save(`prelume-${slug}.pdf`);
}
